### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by Gagandeep1408** [Banuba/agora-plugin-filters-android#2]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.banuba.sdk.agorapluginexample/com.banuba.sdk.agorapluginexample.MainActivity}: java.lang.NullPointerException: <get-agoraRtc>(...) must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2891)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2969)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6735)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
     Caused by: java.lang.NullPointerException: <get-agoraRtc>(...) must not be null
        at com.banuba.sdk.agorapluginexample.MainActivity.getAgoraRtc(MainActivity.kt:46)
        at com.banuba.sdk.agorapluginexample.MainActivity.initAgoraEngine(MainActivity.kt:126)
        at com.banuba.sdk.agorapluginexample.MainActivity.onCreate(MainActivity.kt:99)
        at android.app.Activity.performCreate(Activity.java:6975)

**Comment by Gagandeep1408** [comment]
App crashed after selection filters.
https://docs.google.com/document/d/1jjm566uxcw06modUDOGaHPbOh-f_iYqFiaV8Uvm3mSs/edit?usp=sharing

**Comment by GlebPBanuba** [comment]
Could you please check on the latest version
